### ISSUE TITLE
require加载模块时出现错误

### ISSUE THREAD

**Issue by gczmm** [horan-geeker/nana#17]
loop or previous error loading module 'providers.RouteServiceProvider'

**Comment by junwei000** [comment]
你的代码应该是旧版本的，可以更新下框架，这个问题应该很早就修复了，providers 这个目录也已经被移除了，迁移到新框架你只需要把 routes 路由, controller 控制器, services 逻辑代码, 这些移到新框架下就可以了

**Comment by junwei000** [comment]
有任何疑问可以再重新打开该 issue ，谢谢
