### ISSUE TITLE
请问客户端通过post提交过来的json如何获取呀？

### ISSUE THREAD

**Issue by huahuacn** [horan-geeker/nana#28]
如题，比如客户端有一分json数据叫args，是准备post给服务器的数据。
现在看起来是设定一个params比如叫msg = args是吗？这样会不会就在链接上就明文啦？
另外如果上述问题有解决方案，另一个问题就是如果args是一个二进制数据的话，服务器应该怎么获取呢？
谢谢。

**Comment by junwei000** [comment]
post 在 http 协议里有三种方式把内容放在 body 里，一种是 json，需要加上 http 头 `application/json` 然后 body 里直接放 args 的内容就好了，比如内容是
```
{"foo":"bar"}
```
 框架会把参数解析到 args = request:all() 里，利用 args.foo 就可以取到 bar 这个值
另外两种是 form-data 和 x-www-form-urlencoded 这两个就是你上边说的 msg = args 这样传参，然后服务端可以用 args.msg 取到内容，如果是 json 就自己解析下

**Comment by huahuacn** [comment]
感谢，已经知道怎么做了。
