### ISSUE TITLE
redis多库的时候似乎会出问题呀

### ISSUE THREAD

**Issue by huahuacn** [horan-geeker/nana#29]
如题，我有两个redis，一个是账号数据库A，一个是角色数据库B。
然后注册的时候，我顺序往A和B里面存数据。这个流程是正常的。数据库里面也都有正确的数据。
然后我关掉服务器也关掉数据库，就发现B里面的数据变成和A一模一样了。B里面的正确的数据莫名其妙的丢失了。
请问这个是什么情况你有遇到过吗？

**Comment by junwei000** [comment]
感觉你说的问题不是代码导致的，是关掉服务器也关掉数据库这个动作导致的，那需要看你用的 redis 数据库都在一个 redis 实例里还是两个不同的 ip 实例，如果是两个实例的话可能是你数据库两个实例持久化的文件的路径冲突了

**Comment by huahuacn** [comment]
的确是rdb文件的问题，已解决，谢谢。
